-- GrantGlobe — prototype seed data
-- 25 curated grant records from major UK and international funders.
--
-- HOW TO USE:
--   1. Open the Neon SQL Editor for your project.
--   2. Paste this entire file and click Run.
--   3. Return to GitHub Actions → Refresh grant data and deploy to Pages
--      → Run workflow → Run workflow (green button).
--   4. Wait ~30 seconds, then refresh newlivehung123123.github.io/GrantGlobe_prototype/
--
-- All records carry review_status = 'approved' and requires_review = false,
-- so they pass the export filter in export_grants.py without any manual review step.
-- content_hash is computed via pgcrypto (enabled by the migration).

INSERT INTO grants (
    content_hash,
    grant_title,
    funder_name,
    source_url,
    application_portal_url,
    description,
    application_deadline,
    application_deadline_raw,
    application_deadline_type,
    funding_amount_min,
    funding_amount_max,
    currency,
    funding_amount_type,
    current_status,
    source_language,
    ai_focused,
    individuals_not_eligible,
    organisation_types,
    individual_eligibility,
    applicant_base_regions,
    applicant_base_countries,
    geographic_focus_regions,
    geographic_focus_countries,
    thematic_sectors,
    grant_types,
    confidence_scores,
    aggregate_confidence_score,
    raw_extraction,
    requires_review,
    review_status,
    domain,
    crawl_date
) VALUES

-- 1. Wellcome Trust — Investigator Awards in Science
(
    encode(digest(lower('Wellcome Trust') || '||' || lower('Investigator Awards in Science'), 'sha256'), 'hex'),
    'Investigator Awards in Science',
    'Wellcome Trust',
    'https://wellcome.org/grant-funding/schemes/investigator-awards-science',
    'https://wellcome.org/grant-funding/schemes/investigator-awards-science',
    'Supports outstanding researchers to pursue any direction of science that could significantly improve human or animal health. Awards cover salary, research costs, and indirect costs for 5–7 years.',
    NULL,
    'Rolling — apply at any time',
    'Rolling',
    250000.00, 3000000.00, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research'],
    ARRAY['Research Grant'],
    '{}', 85, '{}', false, 'approved', 'wellcome.org', '2026-05-28'
),

-- 2. Wellcome Trust — Discovery Awards
(
    encode(digest(lower('Wellcome Trust') || '||' || lower('Discovery Awards'), 'sha256'), 'hex'),
    'Discovery Awards',
    'Wellcome Trust',
    'https://wellcome.org/grant-funding/schemes/discovery-awards',
    'https://wellcome.org/grant-funding/schemes/discovery-awards',
    'Funds established research groups to pursue ambitious, long-term programmes with transformative potential for human or animal health. Awards range from £500,000 to £5,000,000 over up to 8 years.',
    NULL,
    'Rolling — apply at any time',
    'Rolling',
    500000.00, 5000000.00, 'GBP', 'Total project costs',
    'Rolling', 'en', false, true,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research'],
    ARRAY['Research Grant'],
    '{}', 85, '{}', false, 'approved', 'wellcome.org', '2026-05-28'
),

-- 3. Wellcome Trust — Mental Health Award
(
    encode(digest(lower('Wellcome Trust') || '||' || lower('Mental Health Award'), 'sha256'), 'hex'),
    'Mental Health Award',
    'Wellcome Trust',
    'https://wellcome.org/grant-funding/schemes/mental-health-award',
    'https://wellcome.org/grant-funding/schemes/mental-health-award',
    'Supports research and innovation to improve the lives of people with depression or anxiety. Focuses on low- and middle-income countries and young people in high-income countries.',
    NULL,
    'Rolling — apply at any time',
    'Rolling',
    NULL, 5000000.00, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute', 'NGO / Civil Society'],
    NULL,
    ARRAY['Global'], NULL,
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research'],
    ARRAY['Research Grant', 'Project Grant'],
    '{}', 80, '{}', false, 'approved', 'wellcome.org', '2026-05-28'
),

-- 4. UKRI — Future Leaders Fellowships
(
    encode(digest(lower('UK Research and Innovation') || '||' || lower('Future Leaders Fellowships'), 'sha256'), 'hex'),
    'Future Leaders Fellowships',
    'UK Research and Innovation',
    'https://www.ukri.org/opportunity/future-leaders-fellowships/',
    'https://www.ukri.org/opportunity/future-leaders-fellowships/',
    'Supports talented early-career researchers and innovators across academia and industry. Awards of £600,000–£1,500,000 over 4–7 years to develop world-class research leaders.',
    '2026-09-30',
    'September 2026 (indicative — deadline varies by round)',
    'Fixed',
    600000.00, 1500000.00, 'GBP', 'Total project costs',
    'Open', 'en', false, false,
    ARRAY['University', 'Research Institute', 'SME'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research', 'Physical Sciences & Engineering', 'Social Sciences', 'Environmental & Climate'],
    ARRAY['Fellowship'],
    '{}', 90, '{}', false, 'approved', 'ukri.org', '2026-05-28'
),

-- 5. ESRC — New Investigator Grants
(
    encode(digest(lower('Economic and Social Research Council') || '||' || lower('New Investigator Grants'), 'sha256'), 'hex'),
    'New Investigator Grants',
    'Economic and Social Research Council',
    'https://www.ukri.org/opportunity/esrc-new-investigator-grants/',
    'https://www.ukri.org/opportunity/esrc-new-investigator-grants/',
    'Provides early-career social scientists with the opportunity to lead their first major independent research project. Awards up to £300,000 for up to 24 months. Three deadlines per year.',
    NULL,
    'Rolling — three deadlines per year',
    'Rolling',
    NULL, 300000.00, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Social Sciences'],
    ARRAY['Research Grant'],
    '{}', 88, '{}', false, 'approved', 'ukri.org', '2026-05-28'
),

-- 6. AHRC — Research Grants
(
    encode(digest(lower('Arts and Humanities Research Council') || '||' || lower('Research Grants'), 'sha256'), 'hex'),
    'Research Grants',
    'Arts and Humanities Research Council',
    'https://www.ukri.org/councils/ahrc/guidance-for-applicants/types-of-funding-we-offer/research-grants/',
    'https://www.ukri.org/councils/ahrc/guidance-for-applicants/types-of-funding-we-offer/research-grants/',
    'Funds high-quality, original research across all areas of the arts and humanities. Standard grants support projects from 12 to 60 months with no fixed upper limit on award value.',
    NULL,
    'Rolling',
    'Rolling',
    NULL, NULL, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Arts & Humanities'],
    ARRAY['Research Grant'],
    '{}', 82, '{}', false, 'approved', 'ukri.org', '2026-05-28'
),

-- 7. BBSRC — Discovery Fellowships
(
    encode(digest(lower('Biotechnology and Biological Sciences Research Council') || '||' || lower('Discovery Fellowships'), 'sha256'), 'hex'),
    'Discovery Fellowships',
    'Biotechnology and Biological Sciences Research Council',
    'https://www.ukri.org/opportunity/bbsrc-discovery-fellowships/',
    'https://www.ukri.org/opportunity/bbsrc-discovery-fellowships/',
    'Supports talented early-career bioscientists to establish an independent research programme. Awards cover salary, research costs, and equipment for up to 5 years.',
    '2026-07-31',
    'July 2026 (indicative)',
    'Fixed',
    NULL, 500000.00, 'GBP', 'Total project costs',
    'Open', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research'],
    ARRAY['Fellowship'],
    '{}', 84, '{}', false, 'approved', 'ukri.org', '2026-05-28'
),

-- 8. EPSRC — Standard Research Grants
(
    encode(digest(lower('Engineering and Physical Sciences Research Council') || '||' || lower('Standard Research Grants'), 'sha256'), 'hex'),
    'Standard Research Grants',
    'Engineering and Physical Sciences Research Council',
    'https://www.ukri.org/councils/epsrc/guidance-for-applicants/types-of-funding-we-offer/research-grants/',
    'https://www.ukri.org/councils/epsrc/guidance-for-applicants/types-of-funding-we-offer/research-grants/',
    'Funds foundational research across engineering and the physical sciences, from mathematics and statistics to manufacturing and materials. No fixed upper limit; proposals assessed by peer review.',
    NULL,
    'Rolling',
    'Rolling',
    NULL, NULL, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Physical Sciences & Engineering', 'Technology & Innovation'],
    ARRAY['Research Grant'],
    '{}', 85, '{}', false, 'approved', 'ukri.org', '2026-05-28'
),

-- 9. NIHR — Research for Patient Benefit
(
    encode(digest(lower('National Institute for Health and Care Research') || '||' || lower('Research for Patient Benefit'), 'sha256'), 'hex'),
    'Research for Patient Benefit',
    'National Institute for Health and Care Research',
    'https://www.nihr.ac.uk/funding/research-for-patient-benefit-rfpb/8780',
    'https://www.nihr.ac.uk/funding/research-for-patient-benefit-rfpb/8780',
    'Funds applied health and social care research with the potential to make a significant difference to NHS patients and service users. Awards up to £500,000 for up to 36 months. Three funding rounds per year.',
    NULL,
    'Rolling — three funding rounds per year',
    'Rolling',
    NULL, 500000.00, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Health & Biomedical Research'],
    ARRAY['Research Grant'],
    '{}', 87, '{}', false, 'approved', 'nihr.ac.uk', '2026-05-28'
),

-- 10. British Academy — Small Research Grants
(
    encode(digest(lower('British Academy') || '||' || lower('Small Research Grants'), 'sha256'), 'hex'),
    'Small Research Grants',
    'British Academy',
    'https://www.thebritishacademy.ac.uk/funding/small-research-grants/',
    'https://www.thebritishacademy.ac.uk/funding/small-research-grants/',
    'Supports primary research in the humanities and social sciences for researchers at UK higher education institutions. Grants of up to £10,000; annual deadline typically in November.',
    '2026-11-15',
    'November 2026',
    'Fixed',
    NULL, 10000.00, 'GBP', 'Total project costs',
    'Open', 'en', false, false,
    ARRAY['University'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Arts & Humanities', 'Social Sciences'],
    ARRAY['Research Grant', 'Seed Funding'],
    '{}', 90, '{}', false, 'approved', 'thebritishacademy.ac.uk', '2026-05-28'
),

-- 11. Royal Society — University Research Fellowships
(
    encode(digest(lower('Royal Society') || '||' || lower('University Research Fellowships'), 'sha256'), 'hex'),
    'University Research Fellowships',
    'Royal Society',
    'https://royalsociety.org/grants/university-research-fellowships/',
    'https://royalsociety.org/grants/university-research-fellowships/',
    'Provides support for outstanding scientists in the early stages of their research career who have the potential to become future leaders in their field. Tenable for up to 8 years.',
    '2026-09-01',
    'September 2026',
    'Fixed',
    NULL, NULL, 'GBP', 'Salary and research costs',
    'Open', 'en', false, false,
    ARRAY['University'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Physical Sciences & Engineering', 'Health & Biomedical Research'],
    ARRAY['Fellowship'],
    '{}', 88, '{}', false, 'approved', 'royalsociety.org', '2026-05-28'
),

-- 12. Leverhulme Trust — Research Fellowships
(
    encode(digest(lower('Leverhulme Trust') || '||' || lower('Research Fellowships'), 'sha256'), 'hex'),
    'Research Fellowships',
    'Leverhulme Trust',
    'https://www.leverhulme.ac.uk/research-fellowships',
    'https://www.leverhulme.ac.uk/research-fellowships',
    'Enables researchers at UK higher education institutions to complete a programme of original research. Provides a replacement salary contribution for up to 24 months; awards typically up to £50,000.',
    '2026-10-31',
    'October 2026',
    'Fixed',
    NULL, 50000.00, 'GBP', 'Salary contribution',
    'Open', 'en', false, false,
    ARRAY['University'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Arts & Humanities', 'Social Sciences', 'Physical Sciences & Engineering'],
    ARRAY['Fellowship'],
    '{}', 88, '{}', false, 'approved', 'leverhulme.ac.uk', '2026-05-28'
),

-- 13. Leverhulme Trust — Research Project Grants
(
    encode(digest(lower('Leverhulme Trust') || '||' || lower('Research Project Grants'), 'sha256'), 'hex'),
    'Research Project Grants',
    'Leverhulme Trust',
    'https://www.leverhulme.ac.uk/research-project-grants',
    'https://www.leverhulme.ac.uk/research-project-grants',
    'Supports innovative and original research projects across any academic discipline. Grants typically range from £100,000 to £500,000 for projects of up to 5 years. Four deadlines per year.',
    NULL,
    'Rolling — four deadlines per year',
    'Rolling',
    100000.00, 500000.00, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Arts & Humanities', 'Social Sciences', 'Physical Sciences & Engineering', 'Health & Biomedical Research'],
    ARRAY['Research Grant'],
    '{}', 90, '{}', false, 'approved', 'leverhulme.ac.uk', '2026-05-28'
),

-- 14. Nuffield Foundation — Open Door
(
    encode(digest(lower('Nuffield Foundation') || '||' || lower('Open Door'), 'sha256'), 'hex'),
    'Open Door',
    'Nuffield Foundation',
    'https://www.nuffieldfoundation.org/funding/open-door',
    'https://www.nuffieldfoundation.org/funding/open-door',
    'Supports exploratory research and evidence synthesis in education, welfare, and justice. Grants up to £50,000 for projects of up to 12 months. Accepts applications from researchers and practitioners at any time.',
    NULL,
    'Rolling',
    'Rolling',
    NULL, 50000.00, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute', 'NGO / Civil Society'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Social Sciences', 'Education'],
    ARRAY['Research Grant', 'Seed Funding'],
    '{}', 85, '{}', false, 'approved', 'nuffieldfoundation.org', '2026-05-28'
),

-- 15. British Heart Foundation — Project Grants
(
    encode(digest(lower('British Heart Foundation') || '||' || lower('Project Grants'), 'sha256'), 'hex'),
    'Project Grants',
    'British Heart Foundation',
    'https://www.bhf.org.uk/for-professionals/information-for-researchers/grant-funding/project-grants',
    'https://www.bhf.org.uk/for-professionals/information-for-researchers/grant-funding/project-grants',
    'Funds high-quality cardiovascular research projects that address specific scientific questions. Awards up to £300,000 for 1–3 years. Three application deadlines per year.',
    NULL,
    'Rolling — three deadlines per year',
    'Rolling',
    NULL, 300000.00, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research'],
    ARRAY['Research Grant', 'Project Grant'],
    '{}', 88, '{}', false, 'approved', 'bhf.org.uk', '2026-05-28'
),

-- 16. Cancer Research UK — Pioneer Award
(
    encode(digest(lower('Cancer Research UK') || '||' || lower('Pioneer Award'), 'sha256'), 'hex'),
    'Pioneer Award',
    'Cancer Research UK',
    'https://www.cancerresearchuk.org/funding-for-researchers/apply-for-funding/types-of-grant/pioneer-award',
    'https://www.cancerresearchuk.org/funding-for-researchers/apply-for-funding/types-of-grant/pioneer-award',
    'Supports high-risk, high-reward cancer research that tests bold ideas and challenges existing paradigms. Awards up to £1,000,000 for up to 5 years. Open to researchers at all career stages.',
    '2026-08-31',
    'August 2026',
    'Fixed',
    NULL, 1000000.00, 'GBP', 'Total project costs',
    'Open', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research'],
    ARRAY['Research Grant'],
    '{}', 83, '{}', false, 'approved', 'cancerresearchuk.org', '2026-05-28'
),

-- 17. ERC — Starting Grants
(
    encode(digest(lower('European Research Council') || '||' || lower('Starting Grants'), 'sha256'), 'hex'),
    'Starting Grants',
    'European Research Council',
    'https://erc.europa.eu/apply-grant/starting-grant',
    'https://erc.europa.eu/apply-grant/starting-grant',
    'Supports early-career researchers with 2–7 years of post-PhD experience who have an excellent scientific track record. Awards up to €1,500,000 for 5 years, across all scientific disciplines.',
    '2026-10-15',
    'October 2026',
    'Fixed',
    NULL, 1500000.00, 'EUR', 'Total project costs',
    'Open', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['Europe'], NULL,
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research', 'Physical Sciences & Engineering', 'Social Sciences', 'Arts & Humanities'],
    ARRAY['Research Grant'],
    '{}', 90, '{}', false, 'approved', 'erc.europa.eu', '2026-05-28'
),

-- 18. ERC — Advanced Grants
(
    encode(digest(lower('European Research Council') || '||' || lower('Advanced Grants'), 'sha256'), 'hex'),
    'Advanced Grants',
    'European Research Council',
    'https://erc.europa.eu/apply-grant/advanced-grant',
    'https://erc.europa.eu/apply-grant/advanced-grant',
    'Supports established research leaders with a proven track record to pursue ambitious, frontier research. Awards up to €2,500,000 for 5 years. Open to researchers of any nationality hosted at a European institution.',
    '2026-12-31',
    'December 2026 (indicative)',
    'Fixed',
    NULL, 2500000.00, 'EUR', 'Total project costs',
    'Upcoming', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['Europe'], NULL,
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research', 'Physical Sciences & Engineering', 'Social Sciences', 'Arts & Humanities'],
    ARRAY['Research Grant'],
    '{}', 90, '{}', false, 'approved', 'erc.europa.eu', '2026-05-28'
),

-- 19. ERC — Proof of Concept Grants
(
    encode(digest(lower('European Research Council') || '||' || lower('Proof of Concept Grants'), 'sha256'), 'hex'),
    'Proof of Concept Grants',
    'European Research Council',
    'https://erc.europa.eu/apply-grant/proof-concept',
    'https://erc.europa.eu/apply-grant/proof-concept',
    'Enables ERC grant holders to explore the commercial or societal potential of their ERC-funded research results. Awards up to €150,000 for 18 months. Exclusively open to current or recent ERC grantees.',
    NULL,
    'Three deadlines per year',
    'Rolling',
    NULL, 150000.00, 'EUR', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute'],
    NULL,
    ARRAY['Europe'], NULL,
    ARRAY['Global'], NULL,
    ARRAY['Technology & Innovation', 'Physical Sciences & Engineering', 'Health & Biomedical Research'],
    ARRAY['Seed Funding'],
    '{}', 88, '{}', false, 'approved', 'erc.europa.eu', '2026-05-28'
),

-- 20. European Commission — Marie Skłodowska-Curie Postdoctoral Fellowships
(
    encode(digest(lower('European Commission') || '||' || lower('Marie Skłodowska-Curie Postdoctoral Fellowships'), 'sha256'), 'hex'),
    'Marie Skłodowska-Curie Postdoctoral Fellowships',
    'European Commission',
    'https://marie-sklodowska-curie-actions.ec.europa.eu/actions/postdoctoral-fellowships',
    'https://marie-sklodowska-curie-actions.ec.europa.eu/actions/postdoctoral-fellowships',
    'Funds experienced researchers to carry out international and interdisciplinary mobility projects. European Fellowships are based at a European host; Global Fellowships include a period at a non-European institution. Annual deadline in September.',
    '2026-09-10',
    'September 2026',
    'Fixed',
    NULL, NULL, 'EUR', 'Salary and research allowances',
    'Open', 'en', false, false,
    ARRAY['University', 'Research Institute', 'SME'],
    NULL,
    ARRAY['Global'], NULL,
    ARRAY['Global'], NULL,
    ARRAY['Health & Biomedical Research', 'Physical Sciences & Engineering', 'Social Sciences', 'Arts & Humanities'],
    ARRAY['Fellowship'],
    '{}', 90, '{}', false, 'approved', 'ec.europa.eu', '2026-05-28'
),

-- 21. European Innovation Council — EIC Pathfinder
(
    encode(digest(lower('European Innovation Council') || '||' || lower('EIC Pathfinder'), 'sha256'), 'hex'),
    'EIC Pathfinder',
    'European Innovation Council',
    'https://eic.ec.europa.eu/eic-funding-opportunities/eic-pathfinder_en',
    'https://eic.ec.europa.eu/eic-funding-opportunities/eic-pathfinder_en',
    'Supports advanced research for visionary and radically new technologies with the potential to create new markets. Pathfinder Open accepts proposals from any field; consortium grants range from €3,000,000 to €4,000,000.',
    NULL,
    'Three cut-off dates per year',
    'Rolling',
    3000000.00, 4000000.00, 'EUR', 'Total project costs',
    'Rolling', 'en', false, true,
    ARRAY['University', 'Research Institute', 'SME'],
    NULL,
    ARRAY['Europe'], NULL,
    ARRAY['Global'], NULL,
    ARRAY['Technology & Innovation', 'Physical Sciences & Engineering'],
    ARRAY['Research Grant'],
    '{}', 85, '{}', false, 'approved', 'eic.ec.europa.eu', '2026-05-28'
),

-- 22. Bill & Melinda Gates Foundation — Grand Challenges Explorations
(
    encode(digest(lower('Bill & Melinda Gates Foundation') || '||' || lower('Grand Challenges Explorations'), 'sha256'), 'hex'),
    'Grand Challenges Explorations',
    'Bill & Melinda Gates Foundation',
    'https://gcgh.grandchallenges.org/about',
    'https://gcgh.grandchallenges.org/challenges',
    'Funds innovative ideas in global health and development. Initial awards of $100,000 with high-performing projects eligible for follow-on grants exceeding $1,000,000. Open to applicants from any discipline worldwide.',
    NULL,
    'Rolling — multiple thematic rounds per year',
    'Rolling',
    NULL, 100000.00, 'USD', 'Initial award',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute', 'NGO / Civil Society', 'SME'],
    NULL,
    ARRAY['Global'], NULL,
    ARRAY['Sub-Saharan Africa', 'South Asia', 'Global'], NULL,
    ARRAY['Health & Biomedical Research', 'International Development'],
    ARRAY['Seed Funding', 'Research Grant'],
    '{}', 85, '{}', false, 'approved', 'grandchallenges.org', '2026-05-28'
),

-- 23. Joseph Rowntree Foundation — Research Grants
(
    encode(digest(lower('Joseph Rowntree Foundation') || '||' || lower('Research Grants'), 'sha256'), 'hex'),
    'Research Grants',
    'Joseph Rowntree Foundation',
    'https://www.jrf.org.uk/funding',
    'https://www.jrf.org.uk/funding',
    'Funds research and innovation to understand and address the causes and consequences of poverty in the UK. JRF supports a range of project scales and methods, with a focus on insights actionable for policy and practice.',
    NULL,
    'Rolling — responsive to JRF programme priorities',
    'Rolling',
    NULL, NULL, 'GBP', 'Total project costs',
    'Rolling', 'en', false, false,
    ARRAY['University', 'Research Institute', 'NGO / Civil Society'],
    NULL,
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['United Kingdom'], ARRAY['GB'],
    ARRAY['Social Sciences', 'Education'],
    ARRAY['Research Grant', 'Project Grant'],
    '{}', 78, '{}', false, 'approved', 'jrf.org.uk', '2026-05-28'
),

-- 24. Open Society Foundations — Open Society Fellowship
(
    encode(digest(lower('Open Society Foundations') || '||' || lower('Open Society Fellowship'), 'sha256'), 'hex'),
    'Open Society Fellowship',
    'Open Society Foundations',
    'https://www.opensocietyfoundations.org/grants/open-society-fellowship',
    'https://www.opensocietyfoundations.org/grants/open-society-fellowship',
    'Supports individuals working on innovative projects that advance open society values including democracy, human rights, and social justice. Fellows receive up to $100,000 for a project period of 6–12 months.',
    NULL,
    'Annual — deadline typically in spring',
    'Rolling',
    NULL, 100000.00, 'USD', 'Total fellowship stipend',
    'Open', 'en', false, false,
    ARRAY['University', 'NGO / Civil Society'],
    ARRAY['Independent Researcher', 'Journalist', 'Practitioner'],
    ARRAY['Global'], NULL,
    ARRAY['Global'], NULL,
    ARRAY['Democracy & Governance', 'Social Sciences'],
    ARRAY['Fellowship'],
    '{}', 80, '{}', false, 'approved', 'opensocietyfoundations.org', '2026-05-28'
),

-- 25. Luminate — Civic Empowerment Grants
(
    encode(digest(lower('Luminate') || '||' || lower('Civic Empowerment Grants'), 'sha256'), 'hex'),
    'Civic Empowerment Grants',
    'Luminate',
    'https://luminategroup.com/funding',
    'https://luminategroup.com/funding',
    'Supports organisations working at the intersection of civic empowerment and data and digital rights. Luminate funds efforts to build transparent, accountable institutions and empower citizens to participate meaningfully in democratic processes.',
    NULL,
    'Rolling — by invitation or open expression of interest',
    'Rolling',
    NULL, NULL, 'USD', 'Total project costs',
    'Rolling', 'en', false, true,
    ARRAY['NGO / Civil Society'],
    NULL,
    ARRAY['Global'], NULL,
    ARRAY['Global'], NULL,
    ARRAY['Democracy & Governance', 'Technology & Innovation'],
    ARRAY['Project Grant'],
    '{}', 75, '{}', false, 'approved', 'luminategroup.com', '2026-05-28'
);
